#!/usr/bin/env perl


our $debug = 0;
our $theme_folder = glob "~/.config/themes";
our $Xresources = glob "~/.Xresources";
our $Xtheme =  "~/.Xtheme";
our $autoload = "~/.scripts/tools/reloadlist.sh" #script to load after the theme has been changed.
chomp(our @themes = `ls $theme_folder`);

chdir glob "~";

sub check_include() {
	unless (`cat $Xresources | grep '#include ".Xtheme"'`) {
		open my $in,  '<',  $Xresources or die "Can't read old file: $!";
		open my $out, '>', "$Xresources.new" or die "Can't write new file: $!";

		print $out "#include \".Xtheme\"\n\n";

		while( <$in> )
		{
			print $out $_;
		}

		close $out;
		close $in;

		print "Include not found, backing up Xresources and adding it to the top.\n";
		`mv $Xresources $Xresources.bak`;
		`mv $Xresources.new $Xresources`;
	}
}

sub process_args() {
	my $arg;
	while (($arg = shift) =~ /-[a-z]/) {
		&print_help() and exit(0) if $arg =~ /-h/;
		&print_list() and exit(0) if $arg =~ /-l/;
		die ("Unknown flag: $arg.");
	}
	die "Please specify a theme to switch to." unless $arg;
	return $arg;
}

sub print_help() {
	print "Usage:\n\tswitchtheme [-lh] [theme]\nFlags:\n\t -h: Print this message.\n\t -l: List available themes.\n";
}

sub print_list() {
	print join("\n", @themes), "\n";
}

my $desired_theme = &process_args(@ARGV);

$found = 0;
for $theme (@themes) {
	$found = 1 if ($theme eq $desired_theme);
	print "$theme, $desired_theme\n" if $debug;
}

die "Theme not found!\n" unless $found;

`rm ~/.Xtheme` if -e glob("~/.Xtheme");
`ln -s $theme_folder/$desired_theme .Xtheme`;
`xrdb ~/.Xresources`;

## Put whatever you wanna reload after a theme switch here
`$autoload`;
